### ISSUE TITLE
Fatal write error on socket transport

### ISSUE THREAD

**Issue by Anhktus** [Snawoot/ssh-tarpit#1]
I'm getting this error from time to time.
`Fatal write error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f6878343a58>
transport: <_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 857, in write
    n = self._sock.send(data)
TimeoutError: [Errno 110] Connection timed out`

I'm running the script with `ssh-tarpit -i 4 -a 192.168.0.201 -p 2222`

After some reading I found a post by someone talking about adding a flow control to solve it.

System infos:

Linux Mint 19.3 Tricia 64-bit
Kernel Linux 5.4.0-65-generic x86_64
AMD Ryzen 5 3600
16GB RAM

**Comment by Sneakometer** [comment]
Got the same error in log. 
Running Debian10/python 3.7.
Installed using pip3

**Comment by Snawoot** [comment]
It's connection timeout, obviously. asyncio already has a flow control.

**Comment by Anhktus** [comment]
still would be nice if your script could handle it better

**Comment by Snawoot** [comment]
@Anhktus like how?

**Comment by Anhktus** [comment]
I never used asyncio but this post suggests to me that you can make use of that flow control in your script so it doesn't causes the error itself.
[https://stackoverflow.com/questions/56526033/asyncio-fatal-error-on-ssl-transport-indexerror-deque-index-out-of-range](https://stackoverflow.com/questions/56526033/asyncio-fatal-error-on-ssl-transport-indexerror-deque-index-out-of-range)

**Comment by Snawoot** [comment]
@Anhktus So, you actually don't know, what you're talking about, right?

**Comment by Anhktus** [comment]
if i would "know" it, i would have fixed it for you.... but i'm not in the mood to get into python just for that.
