### ISSUE TITLE
logfile question

### ISSUE THREAD

**Issue by rj-d2** [Snawoot/ssh-tarpit#10]
hi, i just saw that the github version is 0.4.1 and PyPI is 0.4.0
i updated manually to 0.4.1
changelog says: Multiple logging outputs

i dont get the new logfile documentation,
can i save the log as csv? if so what are the correct arguments?

at the moment i just using ... -f /home/pi/tarpit.log

sry if this is a stupid question

**Comment by Snawoot** [comment]
Hi!

Thanks for letting me know about version mismatch on PyPI. I've updated PyPI just now.

Multiple logging outputs allow logger write log to multiple destinations. For example I can make program output log into console and file simultaneously like this:

```
ssh-tarpit -l "" 1.log
```

CSV logging is not supported.
