### ISSUE TITLE
ssh-tarpit dies when recieving HUP or USR1

### ISSUE THREAD

**Issue by zeus86** [Snawoot/ssh-tarpit#4]
great project. I tried to write a systemd-unit for this, which has a safe way to be reloaded by  logrotate. Unfortunately ssh-tarpit dies when something sends a `HUP`or `USR1` to the process. Most likely on other signals, too. So for now I'm stuck with restarting ssh-tarpit. Restarting is a valid way to handle this, but anyways should PIDs respond correctly to such signals (and not die with an exit!=0).

**Comment by Snawoot** [comment]
Hi!

What this systemd unit is expected to do on reload? If you're using systemd and logs being written via process stderr, it doesn't need any reload signals to reopen logs after logrotate because log files are written by journald.

**Comment by zeus86** [comment]
yeah, you're right, but i wanted to do some statistics afterwards, and i find it easier to work with logfiles. ssh-tarpit gives the option to create one, so i think it should also release it, when a `HUP` signal is given, but yeah, maybe systemd's journals are an option. 

The main benefit of correct `HUP`-handling would be, that clients would remain trapped on log-rotation, because the service would not have to be restarted.

**Comment by zeus86** [comment]
btw. i build a basic ansible-playbook for recent ubuntu-lts. maybe you'll find it useful: https://github.com/zeus86/ansible_ssh-tarpit

**Comment by Snawoot** [comment]
> so i think it should also release it, when a HUP signal is given

That's right. Okay, I'll rework logging facilities. It'll take to use some sort of async queue to work with files w/o suspending event loop while waiting for IO calls. Anyway it's an required exercise to do.

> btw. i build a basic ansible-playbook for recent ubuntu-lts.

Thanks! Need to say that I can't provide any useful feedback on this because I have no experience with Ansible.

**Comment by zeus86** [comment]
> Thanks! Need to say that I can't provide any useful feedback on this because I have no experience with Ansible.
Sure. In current state it won't run on any distribution, but on ubuntu it will deploy ssh-tarpit including a systemd-service with auto-restart on failure and properly configured logrotate.

**Comment by Snawoot** [comment]
I guess I can setup docker image build little bit later.

**Comment by Snawoot** [comment]
HUP support released in v0.4.1
