### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Pandocore** [Snawoot/ssh-tarpit#8]
Hello I use a rpi3 for the SSH tarpit and put 16 ips on it, everything is fine from the start, but after a while I get this error

socket.accept() out of system resource
socket: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.29', 2222)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 179, in _accept_connection
    conn, addr = sock.accept()
  File "/usr/lib/python3.5/socket.py", line 195, in accept
OSError: [Errno 24] Too many open files

in the therminal, is it normal or a bug, can i ignor it or must be split it of more machins ??

**Comment by Snawoot** [comment]
Hello!

It seems you hit open file descriptor limit (ulimit -n). Increase this limit and everything will be alright.

**Comment by Pandocore** [comment]
sorry, i can't follow, what you mean by ulimit -n, i'm using it for the first time today and i'm still inexperienced

**Comment by Pandocore** [comment]
oh sorry, i think i understand you mean in socket.py on line 195 i should enter (ulimit -n) correctly

**Comment by Snawoot** [comment]
It's basic Linux thing: https://linuxhint.com/linux_ulimit_command/
